/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-11-07 19:12:12 UTC)
 * on 2017-11-25 at 02:46:02 UTC 
 * Modify at your own risk.
 */

package com.appspot.car_hub.garagehub.model;

/**
 * Model definition for ModelsUnusedRequest.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the garagehub. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ModelsUnusedRequest extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String unused;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUnused() {
    return unused;
  }

  /**
   * @param unused unused or {@code null} for none
   */
  public ModelsUnusedRequest setUnused(java.lang.String unused) {
    this.unused = unused;
    return this;
  }

  @Override
  public ModelsUnusedRequest set(String fieldName, Object value) {
    return (ModelsUnusedRequest) super.set(fieldName, value);
  }

  @Override
  public ModelsUnusedRequest clone() {
    return (ModelsUnusedRequest) super.clone();
  }

}
